name: Update Google-Scholar citation count

on:
  schedule:
    # runs every day at 03:17 UTC; tweak as you like
    - cron:  '17 3 * * *'
  workflow_dispatch:  # (optional) run manually from the Actions tab

jobs:
  refresh:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          # so we can push back changes
          persist-credentials: false

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --quiet scholarly PyYAML

      - name: Scrape Google Scholar & update _data file
        run: python .github/workflows/update_citations.py
        env:
          SCHOLAR_USER_ID: "D5Fw5_AAAAAJ"   # <-- put your Scholar ID here

      - name: Commit & push if data changed
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: refresh citation count [skip ci]"
          no_push: false
          branch: ${{ github.ref }}
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
