name: Update Google-Scholar citation count

on:
  schedule:
    # runs every day at 03:17 UTC; tweak as you like
    - cron:  '17 3 * * *'
  workflow_dispatch:  # (optional) run manually from the Actions tab

jobs:
  refresh:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          # so we can push back changes
          persist-credentials: false

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies (with proxy-safe httpx)
        run: |
          python -m pip install --quiet "httpx<0.24" scholarly requests PyYAML

      - name: Print versions for debug
        run: |
          python -c "import httpx; print('httpx version:', httpx.__version__)"
          python -c "import scholarly; print('scholarly imported OK')"


      - name: Scrape Google Scholar & update _data file
        run: python .github/workflows/update_citations.py
        env:
          SCHOLAR_USER_ID: "qb_dl6AAAAAJ"   # <-- put your Scholar ID here

      - name: Commit & push if data changed
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: refresh citation count [skip ci]"
          branch: master  # or 'main', as needed
          repository: https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          commit_user_name: github-actions[bot]
          commit_user_email: 41898282+github-actions[bot]@users.noreply.github.com
